// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEHcQL0xphyKNKb3SXgOzirS002txYCA',
    appId: '1:1092328407075:android:fa16682a494750e2ea7196',
    messagingSenderId: '1092328407075',
    projectId: 'belstream-daa04',
    storageBucket: 'belstream-daa04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt7hbgYE11TUJjCFGSBQahIBziWmnq9co',
    appId: '1:1092328407075:ios:10e1b1ed9141c1cfea7196',
    messagingSenderId: '1092328407075',
    projectId: 'belstream-daa04',
    storageBucket: 'belstream-daa04.firebasestorage.app',
    androidClientId: '1092328407075-ktcsg38s6ctdv92jvmd3rojgms732ac4.apps.googleusercontent.com',
    iosClientId: '1092328407075-3o946j66g05vkrafgjfcq0h5e5j5vggk.apps.googleusercontent.com',
    iosBundleId: 'com.livestream.touchvoice',
  );
}
